config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root to: "tasks#index"
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :name, :presence => true

end

app/models/task_spec.rb
require 'rails_helper'

describe Task do
  it {should validate_prescence_of :name }
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def new
    @task = Task.new
  end

  def create
    @tasks = Task.all
    @task = Task.create(task_params)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end


  private
  def task_params
    params.require(:task).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Home</a>
    </div>
            <% if user_signed_in? %>
            <div class="navbar-brand">
              Logged in as <strong><%= current_user.email %></strong>
            </div>
            <div class="navbar-brand">
              <%= link_to 'Edit profile', edit_user_registration_path %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </div>
            <% else %>
            <div class="navbar-brand">
              <%= link_to "Sign up", new_user_registration_path %> |
              <%= link_to "Login", new_user_session_path %>
            </div>
            <% end %>
    </nav>

    <%if notice %>
      <div class="alert alert-info" role="alert">
        <p class="notice"><%= notice %></p>
      </div>
    <%end%>

    <%if alert %>
      <div class="alert alert-info" role="alert">
        <p class="alert"><%= alert %></p>
      </div>
    <%end%>

    <%= yield %>

  </div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
      <div class="form-group">
        <h4><span class="siteform">Task Description:</span>
          <% f.label :name %>
          <%= f.text_field :name %>
        </h4>
      </div>
      <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/tasks/create.js.erb
$('#new_link').show();
$('#task_form').remove();


<% @number = (@tasks.all.length) %>

$('#list_tasks').append('<div id="task<%=@task.id%>" class="task"><%= @number.to_s + ") " + @task.name%> <%= link_to "x", task_path(@task.id), method: "DELETE", class: "btn", remote: true %></div>');

$('.task').last().click(function() {
  $(this).toggleClass('on off');
});

app/views/tasks/destroy.js.erb
$('#task<%= @task.id %>').remove();

app/views/tasks/index.html.erb
<h1>Tasks</h1>

  <% @serial = 0 %>
  <ul id="list_tasks">
    <% @tasks.each do |task| %>
      <div id="task<%=task.id%>">
        <span class="task">
          <% @serial = @serial + 1 %>
          <%= @serial.to_s + ") " + task.name %>
        </span>
          <%= link_to "x", task_path(task.id), method: "DELETE", class: "btn", remote: true %>
        <br>
      </div>
    <%end%>
  </ul>
<br>

<%= link_to "Add Task", new_task_path, id: "new_link", class: "btn btn-primary", remote: true %>

<script>
  $('.task').click(function() {
      $(this).toggleClass('on off');
  });
</script>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<div id="task_form"><%= j render("form") %></div>');